### ISSUE TITLE
Smart Screen Issue

### ISSUE THREAD

**Issue by intervisionlord** [brian-pantano/PianoFromAbove#19]
When i try to launch the installer, my win 10 Smart Screen block this.

**Comment by OSToastBach** [comment]
If you go into the properties of the installer, there should be an "Unblock" check box at the bottom near Apply, after doing this the file should be treated safe by smartscreen, or you could just disable smartscreen alltogether by going into windows settings if you know what you're doing.

**Comment by intervisionlord** [comment]
Thanks.
