### ISSUE TITLE
it has virus

### ISSUE THREAD

**Issue by Sebastian150407** [brian-pantano/PianoFromAbove#51]
your antivirus doesn't detect it but IT HAS VIRUS i passed it from virus total and Hybrid Analysis and VIRUS!!!!!!!!!!!!!

**Comment by LexonBlackzz** [comment]
Your antivirus must be really trash then. There's no viruses, if you're so skeptical/paranoid, compile it yourself. 0 viruses.

**Comment by Sebastian150407** [comment]
> Your antivirus must be really trash then. There's no viruses, if you're so skeptical/paranoid, compile it yourself. 0 viruses.

You know what? F*ck it, i always wanted this program.

**Comment by Sebastian150407** [comment]
im playing rush e rn and is cool

**Comment by Sebastian150407** [comment]
ITS GOOOOD
